FROM openjdk:24-slim

WORKDIR /app
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle .
# Skip build to keep image lean
RUN ./gradlew dependencies --no-daemon

COPY src src

# Run with Spring DevTools
CMD ["sh", "-c", "./gradlew bootRun --no-daemon -x test"]