name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonar-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-java@v4
        name: Set up JDK
        with: { distribution: temurin, java-version: 17 }
      - name: Build & Test
        working-directory: backend
        run: ./gradlew clean build
      - uses: SonarSource/sonarqube-scan-action@v5
        name: Run SonarCloud Scan
        with:
          projectBaseDir: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}