name: Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java (for backend)
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            backend/*.gradle*
            backend/**/gradle-wrapper.properties

      - name: Run Spotless Check
        working-directory: backend
        run: ./gradlew spotlessCheck

      - name: Set up Node.js (for frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Prettier Check
        working-directory: frontend
        run: npx prettier --check .
